### ISSUE TITLE
Add Readme.md

### ISSUE THREAD

**Issue by ghost** [scratcher007lakshya/Foods-Got-Talent#3]
@scratcher007lakshya Iwant to contribute to this website. Iwant to update readme.md file . Please assign it to me ..
Thanks

**Comment by scratcher007lakshya** [comment]
Sure! You Can just fork this site and then The whole website will be yours!!

**Comment by scratcher007lakshya** [comment]
Then After that, Just add the Pull Request...

**Comment by ghost** [comment]
sir please assign it to me so that no other can work on this please

**Comment by scratcher007lakshya** [comment]
But Be Sure, That This is not a Hacktoberfest Repository, if you want your pull request to count on hacktoberfest, Just go to this repo and contribute...
https://github.com/Idhant-6/HAcktoberfest-2021-With-Python

**Comment by scratcher007lakshya** [comment]
you can add also another languages there, and they'll accept it

**Comment by ghost** [comment]
sir but there mention hacktober fest 2021

**Comment by scratcher007lakshya** [comment]
ok, if you want, then you can.....
By the way, I'm  Not sir.. I'm Just A Boy or maybe a student

**Comment by ghost** [comment]
sorry , later i will contribute to your project

**Comment by scratcher007lakshya** [comment]
Ok Sure!
